name: Test dev container templates

on:
  workflow_call:
    inputs:
      template:
        type: string
        description: 'Template to test'
        required: true
        default: 'esp-idf'

  workflow_dispatch:
    inputs:
      template:
        description: 'Template to test'
        required: true
        default: 'esp-idf'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devcontainers CLI
        run: npm install -g @devcontainers/cli

      - name: Copy files
        run: |
          cp -R src/${{ inputs.template }} /tmp/${{ inputs.template }}
          cp -R test/${{ inputs.template }} /tmp/${{ inputs.template }}

      - name: Build template
        run: |
          .github/workflows/build.sh ${{ inputs.template }}

      - name: Launch dev container
        run: devcontainer up --id-label test-container=${{ inputs.template }} --workspace-folder /tmp/${{ inputs.template }}

      - name: Test template
        run: devcontainer exec --workspace-folder /tmp/${{ inputs.template }} --id-label test-container=${{ inputs.template }} "cd /tmp/${{ inputs.template }} && ./test.sh"